export const dataProduct = [
  {
    id: 1,
    name: 'Phần mềm MKT Care',
    msp: 'MKT-CARE',
    mota: 'MKT Care 5.2 ngày 22/06/2023 Update: 1,Đổi pass 2, Mời bạn bè like page 3.share nhiều id bài viết 4. Tham gia nhóm theo từ khóa + trả lời câu hỏi',
    ngaytao: '12/01/2022',
    phienban: '1.0.0',
    status: true,
  },
  {
    id: 2,
    name: 'Phần mềm MKT Data',
    msp: 'MKT-Data',
    mota: 'MKT Care 5.2 ngày 22/06/2023 Update: 1,Đổi pass 2, Mời bạn bè like page 3.share nhiều id bài viết 4. Tham gia nhóm theo từ khóa + trả lời câu hỏi',
    ngaytao: '12/01/2022',
    phienban: '1.0.0',
    status: false,
  },
  {
    id: 3,
    name: 'Phần mềm MKT Viral',
    msp: 'MKT-VIRAL',
    mota: 'Test update MKT Viral',
    ngaytao: '12/01/2022',
    phienban: '1.0.0',
    status: true,
  },
  {
    id: 4,
    name: 'Phần mềm MKT TikTokShop',
    msp: 'MKT-CARE',
    mota: 'MKT Care 5.2 ngày 22/06/2023 Update: 1,Đổi pass 2, Mời bạn bè like page 3.share nhiều id bài viết 4. Tham gia nhóm theo từ khóa + trả lời câu hỏi',
    ngaytao: '12/01/2022',
    phienban: '1.0.0',
    status: true,
  },
  {
    id: 5,
    name: 'Phần mềm MKT BĐS',
    msp: 'MKT-CARE',
    mota: 'MKT Care 5.2 ngày 22/06/2023 Update: 1,Đổi pass 2, Mời bạn bè like page 3.share nhiều id bài viết 4. Tham gia nhóm theo từ khóa + trả lời câu hỏi',
    ngaytao: '12/01/2022',
    phienban: '1.0.0',
    status: true,
  },
  {
    id: 6,
    name: 'Phần mềm MKT Telegram',
    msp: 'MKT-CARE',
    mota: 'MKT Care 5.2 ngày 22/06/2023 Update: 1,Đổi pass 2, Mời bạn bè like page 3.share nhiều id bài viết 4. Tham gia nhóm theo từ khóa + trả lời câu hỏi',
    ngaytao: '12/01/2022',
    phienban: '1.0.0',
    status: true,
  },
];
