export const dataService = [
  {
    id: 1,
    name: 'MKT Data 1 Tháng',
    gia: 500000,
    time: '30',
    sanpham: 'Phần mềm MKT Data',
    status: true,
  },
  {
    id: 2,
    name: 'MKT Viral 1 Tháng',
    gia: 500000,
    time: '30',
    sanpham: 'Phần mềm MKT Viral',
    status: true,
  },
  {
    id: 3,
    name: 'MKT BĐS 1 Tháng',
    gia: 500000,
    time: '30',
    sanpham: 'Phần mềm MKT BĐS',
    status: true,
  },
  {
    id: 4,
    name: 'MKT Tube 1 Tháng',
    gia: 500000,
    time: '30',
    sanpham: 'Phần mềm MKT Tube',
    status: true,
  },
  {
    id: 5,
    name: 'MKT Market 1 Tháng',
    gia: 500000,
    time: '30',
    sanpham: 'Phần mềm MKT Market',
    status: true,
  },
  {
    id: 6,
    name: 'MKT Care 1 Tháng',
    gia: 800000,
    time: '30',
    sanpham: 'Phần mềm MKT Care',
    status: true,
  },
];
