import images from '../images';

export default feckDataKey = [
  {
    id: 1,
    name: 'Nguyễn Mạnh Hổ',
    nameKH: 'Nguyễn Văn Kiên',
    email: 'kienvipaz99@gmail.com',
    goi: 'MKT Care',
    sdt: '0865312138',
    sanpham: 'MKT Care 1 năm',
    ngayban: '30/06/2023',
    giatien: 30000000,
    noidung: 'Nguyễn Văn Kiên chuyển tiền',
    img: [],
    status: false,
    time: 365,
    avt: images.kien,
  },
  {
    id: 2,
    name: 'Nguyễn Mạnh Hổ',
    email: 'kienvipaz99@gmail.com',
    nameKH: 'Nguyễn Văn Kiên',
    goi: 'MKT Care',
    sdt: '0865312138',
    sanpham: 'MKT Care 1 năm',
    ngayban: '30/06/2023',
    giatien: 30000000,
    noidung: 'Nguyễn Văn Kiên chuyển tiền',
    img: [],
    status: false,
    time: 365,
    avt: images.kien,
  },
  {
    id: 3,
    name: 'Nguyễn Mạnh Hổ',
    email: 'kienvipaz99@gmail.com',
    nameKH: 'Nguyễn Văn Kiên',
    goi: 'MKT Care',
    sdt: '0865312138',
    sanpham: 'MKT Care 1 năm',
    ngayban: '30/06/2023',
    giatien: 30000000,
    noidung: 'Nguyễn Văn Kiên chuyển tiền',
    img: [],
    status: true,
    time: 365,
    avt: images.kien,
  },
];
